### ISSUE TITLE
Should read sourcemaps from `compiler.inputFileSystem`

### ISSUE THREAD

**Issue by aletorrado** [webpack-contrib/source-map-loader#103] opened 2020-05-22 21:41 UTC
Hi! This loader is using the default node `fs` module to read the sourcemaps, which breaks compatibility when compiling using virtual filesystems.

It should use the fs API setted on the webpack compiler instance.

**Comment by evilebottnawi** [comment] 2020-05-23 11:03
Yes, it is a bug, duplicate of #2 and will be fixed in the next major release, ETA is the next week

**Closed by evilebottnawi** 2020-05-23 11:03 UTC
